services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - elasticsearch
      - qdrant
      - ollama

  ollama:
    build: ./ollama
    volumes:
      - ./ollama:/app
    ports:
      - "11434:11434"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_storage:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  ollama_storage:
    driver: local
  es_storage:
    driver: local
  qdrant_storage:
    driver: local
