services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    networks:
      - retclean
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: backend
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend:/app
    networks:
      - retclean
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - qdrant

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_storage:/usr/share/elasticsearch/data
    networks:
      - retclean
    ports:
      - "9200:9200"
    
  ollama:
    build: ./ollama
    volumes:
      - ./ollama:/app
    ports:
       - "11434:11434"
   
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - retclean
    ports:
      - "6333:6333"

volumes:
  es_storage:
    driver: local
  qdrant_storage:
    driver: local

networks:
  retclean:
    driver: bridge
